import mongoose from "mongoose";
import { Course } from "../src/models/courseModel.js"; // adjust path as needed
import dotenv from "dotenv";
dotenv.config();

const MONGO_URI = process.env.MONGO_URI || "mongodb://localhost:27017/your_db"; // adjust DB name

const courses = [
  // ── SEMESTER 1 (Common) ──────────────────────────────────────────────────
  {
    course_code: "MA100",
    course_name: "Matrices and Advanced Calculus",
    semester_offered: 1,
    credits: 4,
    course_type: "THEORY",
    department: "APS",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 1, practical: 0 },
  },
  {
    course_code: "PH100",
    course_name: "Engineering Physics",
    semester_offered: 1,
    credits: 3,
    course_type: "THEORY",
    department: "APS",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "EE100",
    course_name: "Basics of Electrical Engineering",
    semester_offered: 1,
    credits: 2,
    course_type: "THEORY",
    department: "EEE",
    nature: "CORE",
    hours: { lecture: 2, tutorial: 0, practical: 0 },
  },
  {
    course_code: "ME100",
    course_name: "Engineering Mechanics",
    semester_offered: 1,
    credits: 3,
    course_type: "THEORY",
    department: "MCE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "CS100",
    course_name: "Computer Programming and Problem",
    semester_offered: 1,
    credits: 3,
    course_type: "THEORY",
    department: "CSE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "HU100",
    course_name: "Liberal Arts",
    semester_offered: 1,
    credits: 1,
    course_type: "THEORY",
    department: "HSS",
    nature: "CORE",
    hours: { lecture: 0, tutorial: 0, practical: 2 },
  },
  {
    course_code: "PH101",
    course_name: "Engineering Physics Lab",
    semester_offered: 1,
    credits: 2,
    course_type: "LAB",
    department: "APS",
    nature: "CORE",
    hours: { lecture: 0, tutorial: 0, practical: 3 },
  },
  {
    course_code: "ME101",
    course_name: "Engineering Drawing",
    semester_offered: 1,
    credits: 3,
    course_type: "LAB",
    department: "MCE",
    nature: "CORE",
    hours: { lecture: 1, tutorial: 0, practical: 3 },
  },
  {
    course_code: "EE101",
    course_name: "Basics of Electrical Engineering Lab",
    semester_offered: 1,
    credits: 1,
    course_type: "LAB",
    department: "EEE",
    nature: "CORE",
    hours: { lecture: 0, tutorial: 0, practical: 3 },
  },
  {
    course_code: "CS101",
    course_name: "Computer Programming Lab",
    semester_offered: 1,
    credits: 1,
    course_type: "LAB",
    department: "CSE",
    nature: "CORE",
    hours: { lecture: 0, tutorial: 0, practical: 2 },
  },

  // ── SEMESTER 2 (Common) ──────────────────────────────────────────────────
  {
    course_code: "MA150",
    course_name: "Differential Equations and Vector Calculus",
    semester_offered: 2,
    credits: 4,
    course_type: "THEORY",
    department: "APS",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 1, practical: 0 },
  },
  {
    course_code: "CY150",
    course_name: "Engineering Chemistry",
    semester_offered: 2,
    credits: 3,
    course_type: "THEORY",
    department: "APS",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "HU150",
    course_name: "Professional Communication",
    semester_offered: 2,
    credits: 4,
    course_type: "THEORY",
    department: "HSS",
    nature: "CORE",
    hours: { lecture: 2, tutorial: 0, practical: 3 },
  },
  {
    course_code: "EC150",
    course_name: "Basics of Electronics Engineering",
    semester_offered: 2,
    credits: 2,
    course_type: "THEORY",
    department: "ECE",
    nature: "CORE",
    hours: { lecture: 2, tutorial: 0, practical: 0 },
  },
  {
    course_code: "ME150",
    course_name: "Basics of Mechanical and Civil",
    semester_offered: 2,
    credits: 3,
    course_type: "THEORY",
    department: "MCE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "HU151",
    course_name: "Health & Happiness",
    semester_offered: 2,
    credits: 2,
    course_type: "THEORY",
    department: "HSS",
    nature: "CORE",
    hours: { lecture: 2, tutorial: 0, practical: 0 },
  },
  {
    course_code: "CY151",
    course_name: "Engineering Chemistry Lab",
    semester_offered: 2,
    credits: 2,
    course_type: "LAB",
    department: "APS",
    nature: "CORE",
    hours: { lecture: 0, tutorial: 0, practical: 3 },
  },
  {
    course_code: "EC151",
    course_name: "Basics of Electronics Engineering Lab",
    semester_offered: 2,
    credits: 1,
    course_type: "LAB",
    department: "ECE",
    nature: "CORE",
    hours: { lecture: 0, tutorial: 0, practical: 3 },
  },
  {
    course_code: "ME151",
    course_name: "Workshop Practices",
    semester_offered: 2,
    credits: 2,
    course_type: "LAB",
    department: "MCE",
    nature: "CORE",
    hours: { lecture: 0, tutorial: 0, practical: 3 },
  },
  {
    course_code: "PE150",
    course_name: "Physical Education",
    semester_offered: 2,
    credits: 0,
    course_type: "THEORY",
    department: "HSS",
    nature: "CORE",
    hours: { lecture: 1, tutorial: 0, practical: 2 },
  },

  // ── SEMESTER 4 — CSE ─────────────────────────────────────────────────────
  {
    course_code: "CS250",
    course_name: "Database Systems",
    semester_offered: 4,
    credits: 4,
    course_type: "THEORY",
    department: "CSE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 1, practical: 0 },
  },
  {
    course_code: "CS251",
    course_name: "Software Engineering",
    semester_offered: 4,
    credits: 3,
    course_type: "THEORY",
    department: "CSE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "CS252",
    course_name: "Computer Organization and Architecture",
    semester_offered: 4,
    credits: 4,
    course_type: "THEORY",
    department: "CSE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 1, practical: 0 },
  },
  {
    course_code: "CS253",
    course_name: "Theory of Computation",
    semester_offered: 4,
    credits: 4,
    course_type: "THEORY",
    department: "CSE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 1, practical: 0 },
  },
  {
    course_code: "CS254",
    course_name: "Microprocessors and Microcontrollers",
    semester_offered: 4,
    credits: 4,
    course_type: "THEORY",
    department: "CSE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 1, practical: 0 },
  },
  {
    course_code: "CS255",
    course_name: "Database Systems Lab",
    semester_offered: 4,
    credits: 2,
    course_type: "LAB",
    department: "CSE",
    nature: "CORE",
    hours: { lecture: 0, tutorial: 0, practical: 3 },
  },
  {
    course_code: "CS256",
    course_name: "Microprocessors and Microcontrollers Lab",
    semester_offered: 4,
    credits: 2,
    course_type: "LAB",
    department: "CSE",
    nature: "CORE",
    hours: { lecture: 0, tutorial: 0, practical: 3 },
  },
  {
    course_code: "CS250M",
    course_name: "Fundamentals of Data Structure",
    semester_offered: 4,
    credits: 4,
    course_type: "THEORY",
    department: "CSE",
    nature: "MINOR",
    hours: { lecture: 3, tutorial: 0, practical: 2 },
  },

  // ── SEMESTER 4 — CVE ─────────────────────────────────────────────────────
  {
    course_code: "CV250",
    course_name: "Computational Methods in Civil Engineering",
    semester_offered: 4,
    credits: 3,
    course_type: "THEORY",
    department: "CVE",
    nature: "CORE",
    hours: { lecture: 2, tutorial: 0, practical: 2 },
  },
  {
    course_code: "IE250",
    course_name: "Innovation and Entrepreneurship",
    semester_offered: 4,
    credits: 1,
    course_type: "THEORY",
    department: "CVE",
    nature: "CORE",
    hours: { lecture: 1, tutorial: 0, practical: 0 },
  },
  {
    course_code: "CV251",
    course_name: "Structural Analysis",
    semester_offered: 4,
    credits: 4,
    course_type: "THEORY",
    department: "CVE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 1, practical: 0 },
  },
  {
    course_code: "CV252",
    course_name: "Geotechnical Engineering",
    semester_offered: 4,
    credits: 3,
    course_type: "THEORY",
    department: "CVE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "CV253",
    course_name: "Environmental Engineering",
    semester_offered: 4,
    credits: 3,
    course_type: "THEORY",
    department: "CVE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "CV254",
    course_name: "Highway Engineering",
    semester_offered: 4,
    credits: 3,
    course_type: "THEORY",
    department: "CVE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "CV255",
    course_name: "Concrete Technology Laboratory",
    semester_offered: 4,
    credits: 2,
    course_type: "LAB",
    department: "CVE",
    nature: "CORE",
    hours: { lecture: 2, tutorial: 0, practical: 0 },
  },
  {
    course_code: "CV256",
    course_name: "Building Design and Drafting Studio",
    semester_offered: 4,
    credits: 2,
    course_type: "LAB",
    department: "CVE",
    nature: "CORE",
    hours: { lecture: 2, tutorial: 0, practical: 0 },
  },

  // ── SEMESTER 4 — EEE ─────────────────────────────────────────────────────
  {
    course_code: "EE250",
    course_name: "Signals & Systems",
    semester_offered: 4,
    credits: 3,
    course_type: "THEORY",
    department: "EEE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "EE251",
    course_name: "Electrical Machines-I",
    semester_offered: 4,
    credits: 3,
    course_type: "THEORY",
    department: "EEE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "EE252",
    course_name: "Digital Systems",
    semester_offered: 4,
    credits: 3,
    course_type: "THEORY",
    department: "EEE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "EE253",
    course_name: "Control Systems",
    semester_offered: 4,
    credits: 4,
    course_type: "THEORY",
    department: "EEE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 1, practical: 0 },
  },
  {
    course_code: "EE254",
    course_name: "Computational Methods",
    semester_offered: 4,
    credits: 3,
    course_type: "THEORY",
    department: "EEE",
    nature: "CORE",
    hours: { lecture: 2, tutorial: 0, practical: 2 },
  },
  {
    course_code: "EE255",
    course_name: "Electrical Machines Lab-I (Workshop)",
    semester_offered: 4,
    credits: 2,
    course_type: "LAB",
    department: "EEE",
    nature: "CORE",
    hours: { lecture: 0, tutorial: 0, practical: 3 },
  },
  {
    course_code: "EE256",
    course_name: "Analog and Digital Circuits Lab",
    semester_offered: 4,
    credits: 2,
    course_type: "LAB",
    department: "EEE",
    nature: "CORE",
    hours: { lecture: 0, tutorial: 0, practical: 3 },
  },
  {
    course_code: "EE257",
    course_name: "Control Systems Lab",
    semester_offered: 4,
    credits: 2,
    course_type: "LAB",
    department: "EEE",
    nature: "CORE",
    hours: { lecture: 0, tutorial: 0, practical: 3 },
  },

  // ── SEMESTER 4 — ECE ─────────────────────────────────────────────────────
  {
    course_code: "EC250",
    course_name: "Numerical Methods for ECE",
    semester_offered: 4,
    credits: 4,
    course_type: "THEORY",
    department: "ECE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 2 },
  },
  {
    course_code: "EC251",
    course_name: "Analog Electronics",
    semester_offered: 4,
    credits: 3,
    course_type: "THEORY",
    department: "ECE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "EC252",
    course_name: "Principle of Communication Systems",
    semester_offered: 4,
    credits: 4,
    course_type: "THEORY",
    department: "ECE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 1, practical: 0 },
  },
  {
    course_code: "EC253",
    course_name: "Sensor Technologies",
    semester_offered: 4,
    credits: 3,
    course_type: "THEORY",
    department: "ECE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "EC254",
    course_name: "Semiconductor Devices",
    semester_offered: 4,
    credits: 4,
    course_type: "THEORY",
    department: "ECE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 1, practical: 0 },
  },
  {
    course_code: "EC255",
    course_name: "Analog Electronics Laboratory",
    semester_offered: 4,
    credits: 2,
    course_type: "LAB",
    department: "ECE",
    nature: "CORE",
    hours: { lecture: 0, tutorial: 0, practical: 3 },
  },
  {
    course_code: "EC256",
    course_name: "Communication Systems Laboratory",
    semester_offered: 4,
    credits: 2,
    course_type: "LAB",
    department: "ECE",
    nature: "CORE",
    hours: { lecture: 0, tutorial: 0, practical: 3 },
  },

  // ── SEMESTER 4 — MCE ─────────────────────────────────────────────────────
  {
    course_code: "ME250",
    course_name: "Computational Methods in Engineering",
    semester_offered: 4,
    credits: 3,
    course_type: "THEORY",
    department: "MCE",
    nature: "CORE",
    hours: { lecture: 2, tutorial: 0, practical: 2 },
  },
  {
    course_code: "ME251",
    course_name: "Design of Machine Elements - I",
    semester_offered: 4,
    credits: 3,
    course_type: "THEORY",
    department: "MCE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "ME252",
    course_name: "Manufacturing Technology-I",
    semester_offered: 4,
    credits: 3,
    course_type: "THEORY",
    department: "MCE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "ME253",
    course_name: "M/C Dynamics & Vibration",
    semester_offered: 4,
    credits: 4,
    course_type: "THEORY",
    department: "MCE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 1, practical: 0 },
  },
  {
    course_code: "ME254",
    course_name: "Applied Thermodynamics",
    semester_offered: 4,
    credits: 3,
    course_type: "THEORY",
    department: "MCE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "ME255",
    course_name: "Thermal Lab-I",
    semester_offered: 4,
    credits: 2,
    course_type: "LAB",
    department: "MCE",
    nature: "CORE",
    hours: { lecture: 0, tutorial: 0, practical: 3 },
  },
  {
    course_code: "ME256",
    course_name: "Machine Shop-1",
    semester_offered: 4,
    credits: 2,
    course_type: "LAB",
    department: "MCE",
    nature: "CORE",
    hours: { lecture: 0, tutorial: 0, practical: 3 },
  },
  {
    course_code: "ME257",
    course_name: "Design Lab-II",
    semester_offered: 4,
    credits: 2,
    course_type: "LAB",
    department: "MCE",
    nature: "CORE",
    hours: { lecture: 0, tutorial: 0, practical: 3 },
  },

  // ── SEMESTER 4 — HSS (shared) ────────────────────────────────────────────
  {
    course_code: "IE250-HSS",
    course_name: "Innovation and Entrepreneurship",
    semester_offered: 4,
    credits: 1,
    course_type: "THEORY",
    department: "HSS",
    nature: "CORE",
    hours: { lecture: 1, tutorial: 0, practical: 0 },
  },
  // NOTE: IE250 also appears for ECE and MCE sem 4 with same code — resolve duplicates if your DB enforces unique course_code

  // ── SEMESTER 6 — CSE ─────────────────────────────────────────────────────
  {
    course_code: "HS350",
    course_name: "Industrial Economics",
    semester_offered: 6,
    credits: 3,
    course_type: "THEORY",
    department: "HSS",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "ES300",
    course_name: "Environmental Studies",
    semester_offered: 6,
    credits: 1,
    course_type: "THEORY",
    department: "APS",
    nature: "CORE",
    hours: { lecture: 1, tutorial: 0, practical: 0 },
  },
  {
    course_code: "CS350",
    course_name: "Distributed Systems",
    semester_offered: 6,
    credits: 3,
    course_type: "THEORY",
    department: "CSE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "CS351",
    course_name: "Compiler Design",
    semester_offered: 6,
    credits: 3,
    course_type: "THEORY",
    department: "CSE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "CS352",
    course_name: "Computer Networks",
    semester_offered: 6,
    credits: 4,
    course_type: "THEORY",
    department: "CSE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 1, practical: 0 },
  },
  {
    course_code: "CS520",
    course_name: "Artificial Intelligence",
    semester_offered: 6,
    credits: 3,
    course_type: "THEORY",
    department: "CSE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "CS353",
    course_name: "Compiler Design Lab",
    semester_offered: 6,
    credits: 2,
    course_type: "LAB",
    department: "CSE",
    nature: "CORE",
    hours: { lecture: 0, tutorial: 0, practical: 3 },
  },
  {
    course_code: "CS354",
    course_name: "Computer Networks Lab",
    semester_offered: 6,
    credits: 2,
    course_type: "LAB",
    department: "CSE",
    nature: "CORE",
    hours: { lecture: 0, tutorial: 0, practical: 3 },
  },
  {
    course_code: "CS350M",
    course_name: "Database Management System",
    semester_offered: 6,
    credits: 4,
    course_type: "THEORY",
    department: "CSE",
    nature: "MINOR",
    hours: { lecture: 3, tutorial: 0, practical: 2 },
  },

  // ── SEMESTER 6 — CVE ─────────────────────────────────────────────────────
  {
    course_code: "HU350",
    course_name: "Human Values and Professional Ethics",
    semester_offered: 6,
    credits: 1,
    course_type: "THEORY",
    department: "CVE",
    nature: "CORE",
    hours: { lecture: 1, tutorial: 0, practical: 0 },
  },
  {
    course_code: "CV350",
    course_name: "Estimation Costing and Specifications",
    semester_offered: 6,
    credits: 4,
    course_type: "THEORY",
    department: "CVE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 1, practical: 0 },
  },
  {
    course_code: "CV351",
    course_name: "Design of Steel Structures",
    semester_offered: 6,
    credits: 4,
    course_type: "THEORY",
    department: "CVE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 1, practical: 0 },
  },
  {
    course_code: "CV352",
    course_name: "Engineering Hydrology and Irrigation Systems",
    semester_offered: 6,
    credits: 4,
    course_type: "THEORY",
    department: "CVE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 1, practical: 0 },
  },
  {
    course_code: "CV507",
    course_name: "Construction Planning and Management",
    semester_offered: 6,
    credits: 3,
    course_type: "THEORY",
    department: "CVE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "CV353",
    course_name: "Structural Design Studio",
    semester_offered: 6,
    credits: 3,
    course_type: "LAB",
    department: "CVE",
    nature: "CORE",
    hours: { lecture: 0, tutorial: 0, practical: 3 },
  },
  {
    course_code: "CV354",
    course_name: "Environmental Engineering Lab",
    semester_offered: 6,
    credits: 2,
    course_type: "LAB",
    department: "CVE",
    nature: "CORE",
    hours: { lecture: 0, tutorial: 0, practical: 3 },
  },
  {
    course_code: "IK351",
    course_name: "Vedic Mathematics",
    semester_offered: 6,
    credits: 3,
    course_type: "THEORY",
    department: "CVE",
    nature: "ELECTIVE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },

  // ── SEMESTER 6 — EEE ─────────────────────────────────────────────────────
  {
    course_code: "EE350",
    course_name: "Electrical System Design",
    semester_offered: 6,
    credits: 3,
    course_type: "THEORY",
    department: "EEE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "EE351",
    course_name: "Electrical Drives",
    semester_offered: 6,
    credits: 3,
    course_type: "THEORY",
    department: "EEE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "EE352",
    course_name: "Power Systems-II",
    semester_offered: 6,
    credits: 4,
    course_type: "THEORY",
    department: "EEE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 1, practical: 0 },
  },
  {
    course_code: "IK35",
    course_name: "Vedic Mathematics",
    semester_offered: 6,
    credits: 3,
    course_type: "THEORY",
    department: "EEE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "EE545",
    course_name: "FPGA based Digital Design",
    semester_offered: 6,
    credits: 3,
    course_type: "THEORY",
    department: "EEE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "EE557",
    course_name: "Cyber Security in Grids",
    semester_offered: 6,
    credits: 3,
    course_type: "THEORY",
    department: "EEE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "EE353",
    course_name: "Power Electronics and Drive Lab",
    semester_offered: 6,
    credits: 2,
    course_type: "LAB",
    department: "EEE",
    nature: "CORE",
    hours: { lecture: 0, tutorial: 0, practical: 3 },
  },
  {
    course_code: "EE354",
    course_name: "Power System Lab",
    semester_offered: 6,
    credits: 2,
    course_type: "LAB",
    department: "EEE",
    nature: "CORE",
    hours: { lecture: 0, tutorial: 0, practical: 3 },
  },
  {
    course_code: "EE355",
    course_name: "Electrical & Electronic Design Lab",
    semester_offered: 6,
    credits: 2,
    course_type: "LAB",
    department: "EEE",
    nature: "CORE",
    hours: { lecture: 0, tutorial: 0, practical: 3 },
  },

  // ── SEMESTER 6 — ECE ─────────────────────────────────────────────────────
  {
    course_code: "EC350",
    course_name: "Digital Communication",
    semester_offered: 6,
    credits: 3,
    course_type: "THEORY",
    department: "ECE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "EC351",
    course_name: "Principles of Antenna and Measurements",
    semester_offered: 6,
    credits: 4,
    course_type: "THEORY",
    department: "ECE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 1, practical: 0 },
  },
  {
    course_code: "EC352",
    course_name: "VLSI Circuit Design",
    semester_offered: 6,
    credits: 3,
    course_type: "THEORY",
    department: "ECE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "EC520",
    course_name: "Digital System Design Using FPGA",
    semester_offered: 6,
    credits: 3,
    course_type: "THEORY",
    department: "ECE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "CS901",
    course_name: "Object Oriented Programming",
    semester_offered: 6,
    credits: 3,
    course_type: "THEORY",
    department: "CSE",
    nature: "ELECTIVE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "EC350M",
    course_name: "Fundamentals of Communication System",
    semester_offered: 6,
    credits: 3,
    course_type: "THEORY",
    department: "ECE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "EC353",
    course_name: "Digital Communication Laboratory",
    semester_offered: 6,
    credits: 2,
    course_type: "LAB",
    department: "ECE",
    nature: "CORE",
    hours: { lecture: 0, tutorial: 0, practical: 3 },
  },
  {
    course_code: "EC354",
    course_name: "High Frequency Laboratory",
    semester_offered: 6,
    credits: 2,
    course_type: "LAB",
    department: "ECE",
    nature: "CORE",
    hours: { lecture: 0, tutorial: 0, practical: 3 },
  },
  {
    course_code: "EC355",
    course_name: "VLSI Circuit Design Laboratory",
    semester_offered: 6,
    credits: 2,
    course_type: "LAB",
    department: "ECE",
    nature: "CORE",
    hours: { lecture: 0, tutorial: 0, practical: 3 },
  },
  // NOTE: EC356 had malformed source data (course_type: "Seminar", lecture field was "Core") — mapped to THEORY/SEMINAR
  {
    course_code: "EC356",
    course_name: "Seminar",
    semester_offered: 6,
    credits: 1,
    course_type: "THEORY",
    department: "ECE",
    nature: "SEMINAR",
    hours: { lecture: 0, tutorial: 0, practical: 2 },
  },

  // ── SEMESTER 6 — MCE ─────────────────────────────────────────────────────
  {
    course_code: "IK351-MCE",
    course_name: "Vedic Mathematics",
    semester_offered: 6,
    credits: 3,
    course_type: "THEORY",
    department: "MCE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "ME350",
    course_name: "Metrology",
    semester_offered: 6,
    credits: 3,
    course_type: "THEORY",
    department: "MCE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "ME351",
    course_name: "Computer Aided Engineering",
    semester_offered: 6,
    credits: 4,
    course_type: "THEORY",
    department: "MCE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 1, practical: 0 },
  },
  {
    course_code: "ME352",
    course_name: "Industrial Engineering",
    semester_offered: 6,
    credits: 3,
    course_type: "THEORY",
    department: "MCE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "ME531",
    course_name: "Internal Combustion Engines",
    semester_offered: 6,
    credits: 3,
    course_type: "THEORY",
    department: "MCE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "ME536",
    course_name: "Finite Element Methods",
    semester_offered: 6,
    credits: 3,
    course_type: "THEORY",
    department: "MCE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "ME353",
    course_name: "Computer Aided Engineering (CAE) Lab",
    semester_offered: 6,
    credits: 2,
    course_type: "LAB",
    department: "MCE",
    nature: "CORE",
    hours: { lecture: 0, tutorial: 0, practical: 3 },
  },
  {
    course_code: "ME354",
    course_name: "Metrology Lab",
    semester_offered: 6,
    credits: 2,
    course_type: "LAB",
    department: "MCE",
    nature: "CORE",
    hours: { lecture: 0, tutorial: 0, practical: 3 },
  },

  // ── SEMESTER 6 — HSS (shared) ────────────────────────────────────────────
  {
    course_code: "HU350-HSS",
    course_name: "Professional Ethics & Human Values",
    semester_offered: 6,
    credits: 1,
    course_type: "THEORY",
    department: "HSS",
    nature: "CORE",
    hours: { lecture: 1, tutorial: 0, practical: 0 },
  },
  {
    course_code: "ES300-HSS",
    course_name: "Environmental Studies",
    semester_offered: 6,
    credits: 1,
    course_type: "THEORY",
    department: "HSS",
    nature: "CORE",
    hours: { lecture: 1, tutorial: 0, practical: 0 },
  },

  // ── SEMESTER 8 — CSE ─────────────────────────────────────────────────────
  {
    course_code: "CS512",
    course_name: "Soft Computing",
    semester_offered: 8,
    credits: 3,
    course_type: "THEORY",
    department: "CSE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "CS529",
    course_name: "Network Security",
    semester_offered: 8,
    credits: 3,
    course_type: "THEORY",
    department: "CSE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "CS513",
    course_name: "Applied Algorithm",
    semester_offered: 8,
    credits: 3,
    course_type: "THEORY",
    department: "CSE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "CS532",
    course_name: "Web Service and Cloud Computing",
    semester_offered: 8,
    credits: 3,
    course_type: "THEORY",
    department: "CSE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "CS450M",
    course_name: "Artificial Intelligence and Machine Learning",
    semester_offered: 8,
    credits: 4,
    course_type: "THEORY",
    department: "CSE",
    nature: "MINOR",
    hours: { lecture: 3, tutorial: 1, practical: 0 },
  },

  // ── SEMESTER 8 — CVE ─────────────────────────────────────────────────────
  {
    course_code: "CV526",
    course_name: "Earthquake Resistant Structures",
    semester_offered: 8,
    credits: 3,
    course_type: "THEORY",
    department: "CVE",
    nature: "ELECTIVE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "CV529",
    course_name: "Advanced Geo-Environmental Engineering",
    semester_offered: 8,
    credits: 3,
    course_type: "THEORY",
    department: "CVE",
    nature: "ELECTIVE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "CV539",
    course_name: "Green Building Design",
    semester_offered: 8,
    credits: 3,
    course_type: "THEORY",
    department: "CVE",
    nature: "ELECTIVE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "CV534",
    course_name: "Rapid Transport System and Smart Cities",
    semester_offered: 8,
    credits: 3,
    course_type: "THEORY",
    department: "CVE",
    nature: "ELECTIVE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "CV541",
    course_name: "Repair and Rehabilitation of Structures",
    semester_offered: 8,
    credits: 3,
    course_type: "THEORY",
    department: "CVE",
    nature: "ELECTIVE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "CV548",
    course_name: "Hazardous Waste Management",
    semester_offered: 8,
    credits: 3,
    course_type: "THEORY",
    department: "CVE",
    nature: "ELECTIVE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  // NOTE: CV499 course_type was "Theory" in source but is a project — mapped to THEORY with nature PROJECT
  {
    course_code: "CV499",
    course_name: "Major Project-II",
    semester_offered: 8,
    credits: 6,
    course_type: "THEORY",
    department: "CVE",
    nature: "PROJECT",
    hours: { lecture: 0, tutorial: 0, practical: 6 },
  },

  // ── SEMESTER 8 — EEE ─────────────────────────────────────────────────────
  {
    course_code: "EE450",
    course_name: "Power System Operation and Control",
    semester_offered: 8,
    credits: 3,
    course_type: "THEORY",
    department: "EEE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "EE522",
    course_name: "Optimization Techniques",
    semester_offered: 8,
    credits: 3,
    course_type: "THEORY",
    department: "EEE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "EE517",
    course_name: "Photovoltaic and its Applications",
    semester_offered: 8,
    credits: 3,
    course_type: "THEORY",
    department: "EEE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "EE502",
    course_name: "Electronic Instrumentation",
    semester_offered: 8,
    credits: 3,
    course_type: "THEORY",
    department: "EEE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "EE512",
    course_name: "High Voltage DC (HVDC) Transmission",
    semester_offered: 8,
    credits: 3,
    course_type: "THEORY",
    department: "EEE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  // NOTE: EE452 course_type was "Project" (not in enum) — mapped to THEORY; nature was CORE but is a project, consider changing to PROJECT
  {
    course_code: "EE452",
    course_name: "Programme Major Project-II",
    semester_offered: 8,
    credits: 6,
    course_type: "THEORY",
    department: "EEE",
    nature: "PROJECT",
    hours: { lecture: 0, tutorial: 0, practical: 6 },
  },

  // ── SEMESTER 8 — ECE ─────────────────────────────────────────────────────
  {
    course_code: "HU401",
    course_name: "Professional Communication-II and Language Lab",
    semester_offered: 8,
    credits: 4,
    course_type: "THEORY",
    department: "ECE",
    nature: "CORE",
    hours: { lecture: 2, tutorial: 0, practical: 3 },
  },
  {
    course_code: "EC405",
    course_name: "Digital System Design",
    semester_offered: 8,
    credits: 3,
    course_type: "THEORY",
    department: "ECE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "EC424",
    course_name: "Low-Power VLSI Circuit Design",
    semester_offered: 8,
    credits: 3,
    course_type: "THEORY",
    department: "ECE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "EC404",
    course_name: "Electronic Instrumentation",
    semester_offered: 8,
    credits: 3,
    course_type: "THEORY",
    department: "ECE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "CS522",
    course_name: "Artificial Intelligence",
    semester_offered: 8,
    credits: 3,
    course_type: "THEORY",
    department: "ECE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  // NOTE: EC499 course_type was "Project" (not in enum) — mapped to THEORY
  {
    course_code: "EC499",
    course_name: "Major Project",
    semester_offered: 8,
    credits: 6,
    course_type: "THEORY",
    department: "ECE",
    nature: "PROJECT",
    hours: { lecture: 0, tutorial: 0, practical: 9 },
  },
  {
    course_code: "EC450M",
    course_name: "Lab Applications of Microcontrollers",
    semester_offered: 8,
    credits: 4,
    course_type: "THEORY",
    department: "ECE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 2 },
  },

  // ── SEMESTER 8 — MCE ─────────────────────────────────────────────────────
  {
    course_code: "ME450",
    course_name: "Industrial Engineering and Operation Research",
    semester_offered: 8,
    credits: 3,
    course_type: "THEORY",
    department: "MCE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "ME527",
    course_name: "Renewable Energy Systems",
    semester_offered: 8,
    credits: 3,
    course_type: "THEORY",
    department: "MCE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "ME522",
    course_name: "Fracture Mechanics",
    semester_offered: 8,
    credits: 3,
    course_type: "THEORY",
    department: "MCE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "ME514",
    course_name: "Mechatronics Engineering",
    semester_offered: 8,
    credits: 3,
    course_type: "THEORY",
    department: "MCE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "ME508",
    course_name: "Supply Chain Management",
    semester_offered: 8,
    credits: 3,
    course_type: "THEORY",
    department: "MCE",
    nature: "CORE",
    hours: { lecture: 3, tutorial: 0, practical: 0 },
  },
  {
    course_code: "ME499",
    course_name: "Major Project-II",
    semester_offered: 8,
    credits: 6,
    course_type: "LAB",
    department: "MCE",
    nature: "PROJECT",
    hours: { lecture: 0, tutorial: 0, practical: 6 },
  },
];

async function seedCourses() {
  try {
    await mongoose.connect(MONGO_URI);
    console.log("✅ Connected to MongoDB");

    await Course.deleteMany({});
    console.log("🗑️  Cleared existing courses");

    const inserted = await Course.insertMany(courses);
    console.log(`🌱 Seeded ${inserted.length} courses successfully`);
  } catch (err) {
    console.error("❌ Seeding failed:", err);
    process.exit(1);
  } finally {
    await mongoose.disconnect();
    console.log("🔌 Disconnected from MongoDB");
  }
}

seedCourses();
